version: '3'

includes:
  github:
    taskfile: github.Taskfile.yml
    dir: .

  bootstrap:
    taskfile: infra/bootstrap/Taskfile.yml
    dir: infra/bootstrap

tasks:
  fixAll:
    desc: Apply all automatic fixes
    deps:
      - github:fixLint
