version: '3'

includes:
  github:
    taskfile: github.Taskfile.yml
    dir: .

  bootstrap-gcp:
    taskfile: infra/bootstrap-gcp/Taskfile.yml
    dir: infra/bootstrap-gcp

tasks:
  fixAll:
    desc: Apply all automatic fixes
    deps:
      - github:fixLint
