version: '3'

env:
  # No secrets yet
  PULUMI_CONFIG_PASSPHRASE: ""

tasks:
  install:
    internal: true
    run: once
    dir: ..
    sources:
      - package.json
      - '*/package.json'
      - yarn.lock
    generates:
      - .yarn/install-state.gz
    cmds:
      - corepack yarn install --immutable

  selectStack:
    internal: true
    run: once
    cmds:
      - pulumi stack select --non-interactive main

  infraPreview:
    desc: Preview changes to the stack
    deps: [install, selectStack]
    cmds:
      - pulumi preview --non-interactive {{.CLI_ARGS}}
