name: Preview foundation

on:
  workflow_call:

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  NO_COLOR: 1
  PULUMI_CONFIG_PASSPHRASE: ""
  GCP_IDENTITY_PROVIDER: projects/626887270411/locations/global/workloadIdentityPools/github/providers/github-actions

jobs:
  preview-foundation:
    name: Preview foundation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version-file: infra/foundation/.nvmrc

      - name: Install dependencies
        working-directory: infra/foundation
        run: corepack yarn install --immutable

      - name: Log in to GCP as the organization reader
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ env.GCP_IDENTITY_PROVIDER }}
          service_account: organization-reader@ms-root-f69f2a6d.iam.gserviceaccount.com

      - name: Preview
        uses: pulumi/actions@v7.0.0
        with:
          command: preview
          stack-name: main
          work-dir: infra/foundation
          cloud-url: gs://ms-root-foundation-state-b2099013
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
